name: Build ARM64 NAPI Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Install Cross Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install dependencies
        run: yarn install

      - name: Build NAPI module for ARM64
        run: |
          yarn build --target aarch64-unknown-linux-gnu
